language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


  #before_script:
  # - npm install -g gulp

script:
  - hexo g -d

after_script:
  - cd ./public
  - git init
  - git config user.name "jinghongdaxiong"
  - git config user.email "xuxiongzi@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://github.com/jinghongdaxiong/jinghongdaxiong.github.io.git" hexo:hexo
#  - git push --force --quiet "https://${githubblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-resource
env:
  global:
    - GH_REF: github.com/jinghongdaxiong/jinghongdaxiong.github.io.git
